version: '3'
services:
  wsgi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ${MEDIA_PATH}:/app/media/
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:8000