version: '3'
services:
  wsgi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ${MEDIA_PATH}:/app/media/
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:8000

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A mephi_ifib.celery.app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ${MEDIA_PATH}:/app/media/

volumes:
  redis_data: