# Generated by Django 5.1.1 on 2024-09-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="description",
            field=models.CharField(
                default="", max_length=255, verbose_name="Должность"
            ),
            preserve_default=False,
        ),
    ]
