# Generated by Django 5.1.1 on 2024-09-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0003_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("text", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, verbose_name="Обращение закрыто"
                    ),
                ),
            ],
        ),
    ]
