# Generated by Django 5.1.1 on 2024-10-01 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0004_feedbackform"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("radionuclides_diagnosis", "radionuclides_diagnosis"),
                            ("radiation_therapy", "radiation_therapy"),
                            ("ultra_sound_diagnosis", "ultra_sound_diagnosis"),
                            ("mri_diagnosis", "mri_diagnosis"),
                            ("safety", "safety"),
                            ("regulatory_documents", "regulatory_documents"),
                        ],
                        max_length=23,
                        unique=True,
                        verbose_name="Название раздела",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "База знаний",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackform",
            options={"verbose_name_plural": "Обратная связь"},
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Отправитель"),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="phone_number",
            field=models.CharField(
                help_text="Указан без +7", max_length=10, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="text",
            field=models.TextField(verbose_name="Текст обращения"),
        ),
        migrations.CreateModel(
            name="Terms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Термин")),
                ("description", models.TextField(verbose_name="Определение")),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ifib.knowledgebase",
                        verbose_name="Раздел базы знаний",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Термины",
            },
        ),
    ]
