# Generated by Django 5.1.1 on 2024-10-01 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0005_knowledgebase_alter_feedbackform_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registration_token",
            field=models.UUIDField(
                default=uuid.UUID("86f70926-af4d-4c28-a87b-4371e3d739b4"), null=True
            ),
        ),
    ]
