# Generated by Django 5.1.1 on 2024-10-04 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0006_alter_user_registration_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="terms",
            old_name="description",
            new_name="definition",
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="name",
            field=models.CharField(
                choices=[
                    (1, "Радионуклидная диагностика и терапия"),
                    (2, "Лучевая терапия"),
                    (3, "УЗИ"),
                    (4, "МРТ"),
                    (5, "Техника безопасности"),
                    (6, "Нормативно-правовые документы"),
                ],
                max_length=36,
                unique=True,
                verbose_name="Название раздела",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_token",
            field=models.UUIDField(
                default=uuid.UUID("3174e30f-b28a-41cb-8b2f-88cacbc34d5b"), null=True
            ),
        ),
    ]
