# Generated by Django 5.1.1 on 2024-11-12 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0007_rename_description_terms_definition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Films",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "theme",
                    models.CharField(max_length=255, verbose_name="Тематика/участники"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "cover",
                    models.ImageField(
                        upload_to="nuclear_medicine_intro/films/",
                        verbose_name="Обложка",
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка на видео")),
            ],
            options={
                "verbose_name_plural": "Видео",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=models.ImageField(
                upload_to="nuclear_medicine_intro/article/covers/",
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.ImageField(
                upload_to="home/team_members/", verbose_name="Фото"
            ),
        ),
    ]
