# Generated by Django 5.1.1 on 2024-10-04 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0007_rename_description_terms_definition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name_plural": "Группа оборудования",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=models.ImageField(
                upload_to="nuclear_medicine_intro/article/covers/",
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="document",
            field=models.FileField(
                help_text="Формат: PDF",
                upload_to="nuclear_medicine_intro/article/documents/",
                verbose_name="Документ",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.ImageField(
                upload_to="home/team_members/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_token",
            field=models.UUIDField(
                default=uuid.UUID("a6771ee6-84fd-4e98-aa03-9202d7b76729"), null=True
            ),
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "cover",
                    models.ImageField(
                        upload_to="nuclear_medicine_intro/equipment/covers",
                        verbose_name="Обложка/изображение модели",
                    ),
                ),
                (
                    "model",
                    models.FileField(
                        upload_to="nuclear_medicine_intro/equipment/models",
                        verbose_name="Файл с 3D-моделью",
                    ),
                ),
                (
                    "equipment_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ifib.equipmentgroup",
                        verbose_name="Группа оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Оборудование",
            },
        ),
    ]
