# Generated by Django 5.1.1 on 2024-10-04 20:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0008_equipmentgroup_alter_article_cover_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name_plural": "Оборудование (3D-модели)"},
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_token",
            field=models.UUIDField(
                default=uuid.UUID("f997a093-7187-4648-a74f-7bcac7bbefcb"), null=True
            ),
        ),
    ]
