# Generated by Django 5.1.1 on 2024-11-13 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0008_films_alter_article_cover_alter_teammember_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_group",
                    models.CharField(
                        choices=[
                            ("scintigraphy", "Сцинтиграфия"),
                            (
                                "single_photon_emission_tomography",
                                "Однофотонная эмиссионная томография",
                            ),
                            (
                                "positron_emission_tomography",
                                "Позитронная эмиссионная томография",
                            ),
                            ("computed_tomography", "Компьютерная томография"),
                            ("mri", "Магнитно-резонансная томография"),
                            ("radiation_therapy", "Дистанционная лучевая терапия"),
                        ],
                        max_length=255,
                        verbose_name="Группа оборудования",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "cover",
                    models.ImageField(
                        upload_to="nuclear_medicine_intro/equipment/",
                        verbose_name="Обложка/изображение модели",
                    ),
                ),
                ("model", models.URLField(verbose_name="Ссылка на 3D-модель")),
            ],
            options={
                "verbose_name_plural": "Оборудование",
            },
        ),
    ]
