# Generated by Django 5.1.1 on 2024-10-04 20:02

import uuid
from enum import Enum

from django.db import migrations, models

from ifib.enums import RoleEnum, KnowledgeBaseEnum, EquipmentGroupEnum


def add_records_from_enum(apps, enum: type[Enum], model_name: str):
    model = apps.get_model("ifib", model_name)
    for record in enum:
        model.objects.get_or_create(id=record.value, name=record.name)


def add_initial_data(apps, schema_editor):
    add_records_from_enum(apps, RoleEnum, "Role")
    add_records_from_enum(apps, KnowledgeBaseEnum, "KnowledgeBase")
    add_records_from_enum(apps, EquipmentGroupEnum, "EquipmentGroup")


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0009_alter_equipment_options_and_more"),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
