# Generated by Django 5.1.1 on 2024-11-13 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifib", "0010_practice_alter_user_registration_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcasts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "description",
                    models.TextField(verbose_name="Описание (автор, тематика)"),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="nuclear_medicine_intro/podcasts/",
                        verbose_name="Обложка",
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка на подкаст")),
            ],
            options={
                "verbose_name_plural": "Подкасты",
            },
        ),
    ]
