openapi: 3.0.1
info:
  title: Mephi-IFIB API
  version: '1.0'
paths:
  /api/v1/auth/register:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
        required: true
      responses:
        '200':
          description: successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterAuthResponse'
  /api/v1/auth/register/confirm:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationConfirmRequest'
        required: true
      responses:
        '200':
          description: successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
  /api/v1/auth/update-confirmation-code:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConfirmationCodeRequest'
        required: true
      responses:
        '200':
          description: successful request
  /api/v1/auth/login:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
  /api/v1/home/media/main-video:
    get:
      tags:
        - home
      responses:
        '200':
          description: successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoLink'
  /api/v1/home/team:
    get:
      tags:
        - home
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamMember'
  /api/v1/home/feedback-form:
    post:
      tags:
        - home
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedbackRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedObject'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegistrationRequest:
      type: object
      required:
        - first_name
        - last_name
        - birth_date
        - mobile_phone
        - grade
        - sphere_of_interest
        - email
        - password
        - password2
      properties:
        first_name:
          type: string
        middle_name:
          type: string
        last_name:
          type: string
        birth_date:
          type: string
          format: date
          example: 05.03.2003
        mobile_phone:
          type: string
        grade:
          type: string
        sphere_of_interest:
          type: string
          enum:
            - it
            - science
            - art
            - sport
            - music
        email:
          type: string
        password:
          type: string
        password_2:
          type: string

    RegistrationConfirmRequest:
      type: object
      required:
        - confirmationCode
        - registerToken
      properties:
        confirmationCode:
          type: string
        registerToken:
          type: string

    UpdateConfirmationCodeRequest:
      type: object
      required:
        - registerToken
      properties:
        registerToken:
          type: string

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    FeedbackRequest:
      type: object
      properties:
        name:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        text:
          type: string

    VideoLink:
      type: object
      properties:
        url:
          type: string

    TeamMember:
      type: object
      properties:
        name:
          type: string
        image:
          type: string
          format: binary

    RegisterAuthResponse:
      type: object
      properties:
        registerToken:
          type: string

    TokenResponse:
      type: object
      properties:
        token:
          type: string

    CreatedObject:
      properties:
        id:
          type: integer

    Error:
      properties:
        type:
          type: integer
        message:
          type: string